name: ToXiiCMines
version: 1.0.0
description: Custom Mine Reset Plugin.
author: ToXiiCxNetwork
authors: [ToXiiCxNetwork]

main: net.toxiic.mines.Main
database: false
depend: [Vault, PlaceholderAPI]

commands:
  ToXiiCMines:
    description: Reset Mine.
    aliases: [tm]